version: '3.8'

services:
  app:
    image: 'petclinic:latest'
    build:
      context: ./petclinic
    ports:
      - 8444:8444
    depends_on:
      - postgres
      - zookeeper
      - kafka
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      
  vet-service:
    image: 'vet-service:latest'
    build: ./petclinic-vet-service
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - app
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      
  type-service:
    image: 'type-service:latest'
    build: ./petclinic-type-service
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - app
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
          
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    volumes:
      - ./postgres/sql-init:/docker-entrypoint-initdb.d
      - ./postgres/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=petclinic
      - PGDATA=/var/lib/postgresql/data/pgdata

  keycloak:
    image: jboss/keycloak:11.0.2
    ports:
      - 8443:8443
    volumes:
      - ./keycloak/certs:/etc/x509/https
      - ./keycloak/ca_certs:/var/ca_certs
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - X509_CA_BUNDLE=/var/ca_certs/petclinic.crt
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    volumes:
      - ./keycloak/kc_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
      - PGDATA=/var/lib/postgresql/data/pgdata
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
